# Generated by Django 3.0.6 on 2020-06-23 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloTiempo',
            fields=[
                ('id_modulo', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_inicio', models.DateField()),
                ('hora_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('patente', models.CharField(help_text='Ingrese Patente', max_length=30)),
                ('marca', models.CharField(help_text='Ingrese marca', max_length=30)),
                ('modelo', models.CharField(help_text='Ingrese modelo', max_length=30)),
                ('modulo_tiempo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reserva.ModuloTiempo')),
                ('rut_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
