# Generated by Django 3.0.6 on 2020-06-24 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20200601_2035'),
        ('reserva', '0002_auto_20200623_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicio.Servicio'),
        ),
    ]
