# Generated by Django 3.0.6 on 2020-06-25 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicio', '0003_auto_20200601_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('total', models.IntegerField()),
                ('usuario_rut_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vunitario', models.IntegerField()),
                ('desc_prod', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('totallinea', models.IntegerField()),
                ('boleta_id_boleta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='boleta.Boleta')),
                ('servicio_id_servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.Servicio')),
            ],
        ),
    ]
