# Generated by Django 3.0.6 on 2020-06-28 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boleta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='usuario_rut_usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='detalleboleta',
            old_name='servicio_id_servicio',
            new_name='servicio',
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='desc_prod',
            field=models.CharField(help_text='Ingrese descuento', max_length=30),
        ),
    ]
