# Generated by Django 3.0.6 on 2020-07-04 01:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_remove_producto_codigo_producto'),
        ('boleta', '0002_auto_20200627_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleboleta',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
