# Generated by Django 3.0.6 on 2020-07-09 00:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_remove_producto_codigo_producto'),
        ('boleta', '0002_auto_20200627_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleboleta',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.Producto'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de boleta'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='id_boleta',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='desc_prod',
            field=models.CharField(max_length=30, verbose_name='Descripción producto'),
        ),
        migrations.AlterField(
            model_name='detalleboleta',
            name='vunitario',
            field=models.PositiveIntegerField(verbose_name='Precio'),
        ),
    ]
