# Generated by Django 3.0.5 on 2020-04-29 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese el nombre del producto', max_length=20)),
                ('valor_compra', models.IntegerField()),
                ('valor_venta', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stock_critico', models.IntegerField()),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
        ),
    ]
