# Generated by Django 2.2.7 on 2020-05-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id_estado_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese estado del producto', max_length=30)),
            ],
        ),
    ]
