# Generated by Django 2.2.7 on 2020-05-01 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_estadoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_estado_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.EstadoProducto'),
        ),
    ]
