# Generated by Django 2.2.7 on 2020-05-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_id_estado_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='codigo_producto',
        ),
    ]
