# Generated by Django 3.0.8 on 2020-07-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_auto_20200719_0044'),
        ('proveedor', '0003_auto_20200719_0013'),
    ]

    operations = [
    ]
