# Generated by Django 3.0.6 on 2020-07-20 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_auto_20200719_0044'),
        ('proveedor', '0003_auto_20200719_0013'),
    ]

    operations = [
    ]
