# Generated by Django 3.0.8 on 2020-07-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_merge_20200721_1623'),
        ('proveedor', '0004_merge_20200720_1917'),
    ]

    operations = [
    ]
