# Generated by Django 3.0.6 on 2020-05-14 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoServicio',
            fields=[
                ('id_estado_servicio', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(help_text='Ingrese descripcion', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.IntegerField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(help_text='Ingrese nombre de servicio', max_length=20)),
                ('valor_servicio', models.IntegerField()),
                ('id_estado_servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicio.EstadoServicio')),
            ],
        ),
    ]
