# Generated by Django 3.0.6 on 2020-05-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='id_servicio',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
