# Generated by Django 3.0.6 on 2020-06-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_auto_20200514_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(help_text='Ingrese nombre de servicio', max_length=50),
        ),
    ]
