# Generated by Django 3.0.6 on 2020-07-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_auto_20200601_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='nombre_servicio',
            field=models.CharField(help_text='Ingrese nombre de servicio', max_length=50, unique=True),
        ),
    ]
